version: "3"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mysql

  client:
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
